title: "프로그램 구성하기"
description: "UC Berkeley CS61A 교과서의 한국어 초월번역"
theme: jekyll-theme-minimal

# [중요] 아래 두 줄이 주소 생성의 핵심입니다.
url: "https://noelclay.github.io"
baseurl: "/ucb_cs61a_fall2022"

# 플러그인 설정
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
